name: Update jupyter-pod template

on:
  push:
    branches:
      - main
    paths:
        - "tempaltes/jupyter-pod/main.tf"
        - ".github/workflows/jupyter-pod.yml"
  workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Get latest commit hash
          id: latest_commit
          run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        - name: Get commit title
          id: commit_title
          run: echo "title=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

        - name: Update Coder Template
          uses: matifali/update-coder-template@v3
          with:
            id: jupyter-pod
            dir: templates/jupyter-pod
            url: https://eric-aks.demo.coder.com
            name: ${{ steps.latest_commit.outputs.hash }}
            message: ${{ steps.commit_title.outputs.title }}
            coder_session_token: ${{ secrets.CODER_SESSION_TOKEN }}